# Generated by Django 4.0.3 on 2023-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100000)),
                ('b_descp', models.TextField()),
                ('b_author', models.CharField(max_length=5000)),
                ('b_date', models.DateField()),
                ('b_photo', models.FileField(upload_to='images/%y')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
