# Generated by Django 4.0.3 on 2023-07-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_b_descp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_date',
            field=models.DateField(default='No description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='b_descp',
            field=models.TextField(),
        ),
    ]
